"""empty message

Revision ID: 05d3ee87a666
Revises: 1aa986810f75
Create Date: 2022-04-16 01:48:05.367057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d3ee87a666'
down_revision = '1aa986810f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('description', sa.String(), nullable=True))
    op.add_column('planet', sa.Column('description', sa.String(), nullable=True))
    op.add_column('vehicle', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'description')
    op.drop_column('planet', 'description')
    op.drop_column('character', 'description')
    # ### end Alembic commands ###
