"""empty message

Revision ID: 1aa986810f75
Revises: f4f16b719b25
Create Date: 2022-04-16 01:25:21.003020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa986810f75'
down_revision = 'f4f16b719b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('length', sa.String(length=250), nullable=True))
    op.drop_column('vehicle', 'lenth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('lenth', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('vehicle', 'length')
    # ### end Alembic commands ###
