"""empty message

Revision ID: 52cb1b09720d
Revises: 22b7d3f5dd5d
Create Date: 2022-03-14 23:29:18.542853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cb1b09720d'
down_revision = '22b7d3f5dd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('planet', 'url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('vehicle', 'url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle', 'url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planet', 'url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
