"""empty message

Revision ID: 85cfa2492601
Revises: 52cb1b09720d
Create Date: 2022-04-15 15:16:27.226746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85cfa2492601'
down_revision = '52cb1b09720d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('pilots', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'pilots')
    # ### end Alembic commands ###
