"""empty message

Revision ID: f4f16b719b25
Revises: 85cfa2492601
Create Date: 2022-04-15 23:06:59.981610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f16b719b25'
down_revision = '85cfa2492601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('uid', sa.Integer(), nullable=True))
    op.add_column('planet', sa.Column('uid', sa.Integer(), nullable=True))
    op.add_column('vehicle', sa.Column('uid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'uid')
    op.drop_column('planet', 'uid')
    op.drop_column('character', 'uid')
    # ### end Alembic commands ###
